// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twtdieeigbjleaqhymxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3dGRpZWVpZ2JqbGVhcWh5bXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjg5NDEsImV4cCI6MjA2NTkwNDk0MX0.y5ldCYaGMUDJlYYmsu0Y4DUPN0WYDGSGRy6PoQE1RXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);